create table if not exists zoho_tokens (
  id bigint generated by default as identity primary key,
  user_mail text not null,
  client_id text,
  refresh_token text,
  access_token text,
  grant_token text,
  expiry_time text
);
